---
language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - bower_components
    - node_modules
sudo: false

before_script:
  - npm install

# Install the travis gem.
# Create a deploy key and encrypt it with:
# $ travis encrypt-file .deploy_key
# Commit the encrypted file and
# replace the key id in the third command below with the generated one.
before_install:
  - nvm install
  - if [ ! -z "${DEPLOY_KEY}" ]; then eval "$(ssh-agent)"; fi
  - ./.travis_key.sh 688b2cacd9aa
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis
